export const roomData = [
  {
    id: "1",
    type: 2,
    name: "普通雙人房",
    num: 2,
    bed: "一大床",
    squareSize: 12,
    src: require("../images/doubleRoom.png"),
  },
  {
    id: "2",
    type: 2,
    name: "日式雙人房",
    num: 2,
    bed: "一大床",
    squareSize: 12,
    src: require("../images/doubleRoomJP.png"),
  },
  {
    id: "3",
    type: 3,
    name: "普通四人房",
    num: 4,
    bed: "兩大床",
    squareSize: 19,
    src: require("../images/quadrupleRoom.png"),
  },
  {
    id: "4",
    type: 3,
    name: "日式四人房",
    num: 4,
    bed: "兩大床",
    squareSize: 19,
    src: require("../images/quadrupleRoomJP.png"),
  },
];
